version:  '3'

services: 
  db:
    image: mariadb:latest
    restart: always
    env_file: 
      - .env

  dc-timeline:
    depends_on: 
      - db
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: gcplogs
      options:
        gcp-meta-name: discord-timeline
    restart: always
    env_file: 
      - .env
    environment: 
      MYSQL_ADDRESS: db
